runtime: java
env: flex

runtime_config:
  jdk: openjdk8
  server: tomcat

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
- url: /.*
  script: this field is required, but ignored
